# Generated by Django 5.2.3 on 2025-10-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Телеграм id'),
        ),
    ]
