# Generated by Django 5.2.3 on 2025-06-17 04:41

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=160, null=True, verbose_name='Место где выполняется привычка')),
                ('time', models.TimeField(help_text='в формате чч:мм', null=True, verbose_name='время')),
                ('action', models.CharField(max_length=160, verbose_name='Привычка')),
                ('pleasantness', models.BooleanField(default=False, help_text='Признак приятной привычки')),
                ('periodicity', models.PositiveSmallIntegerField(choices=[(1, 'ежедневно'), (2, 'через день'), (3, 'раз в 3 дня'), (4, 'раз в 4 дня'), (5, 'раз в 5 дней'), (6, 'раз в 6 дней'), (7, 'еженедельно')], default=1, help_text='Периодичность: 1-ежедневно, 7-еженедельно', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('reward', models.TextField(blank=True, null=True, verbose_name='Вознаграждение за выполненную привычку')),
                ('time_to_complete', models.DurationField(blank=True, help_text='Формат: ЧЧ:ММ:СС (например, 00:01:00 — 1 минута)', null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.timedelta(seconds=120))])),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('last_remember', models.DateTimeField(blank=True, help_text='Когда в последний раз было отправлено напоминание', null=True, verbose_name='Последнее напоминание')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('sheaf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
