# Generated by Django 5.2.3 on 2025-10-02 04:40

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='sheaf',
        ),
        migrations.AddField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Связанная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Место где выполняется привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(blank=True, help_text='в формате чч:мм', null=True, verbose_name='время'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.DurationField(blank=True, help_text='Формат: ЧЧ:ММ:СС (например, 00:01:00 — 1 минута)', null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.timedelta(seconds=120))]),
        ),
    ]
