# Generated by Django 5.2.3 on 2025-10-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_habit_sheaf_habit_related_habit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.TextField(blank=True, null=True, verbose_name='Вознаграждение за выполненную привычку!'),
        ),
    ]
